### PR TITLE
Test for 'Verifying a single transaction'; minor improvements

### PR DESCRIPTION
**Pull request by pmikolajczyk41**
## Description

When working on the exercises I encountered two annoying things:
 - `cargo` was continually complaining about some small problems (even after completing exercise)
 - 2nd exercise ('Verifying a single transaction') couldn't have been tested separately from the 3rd one

This PR:
 - calms down `cargo clippy` as much as possible (i.e. after completing the exercises, there should be no warnings)
 - introduces `UnaryRollup` which is a simplified version of `Rollup` - this one serves for testing 2nd exercise
 - adds a unit test for the 2nd exercise using `UnaryRollup`
 - fixes rendering of some READMEs

Checklist:

- [x] Targeted PR against correct branch (main)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests (n/a - typos and unit test itself)
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md` (n/a - seems to be unmaintained)
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by weikengchen** [comment]
Let me clean it up a bit, apparently the remaining tests have been failing for more than one year.

**Comment by pmikolajczyk41** [comment]
@weikengchen I'm afraid that `unused variable` is the thing that we should ignore in CI (or prepend corresponding object names with `_`), at least for such (tutorial) repository

I'm not so sure about `no-std` checks though

**Comment by weikengchen** [comment]
Let me merge it first. The `no-std` check is pretty weird, and I believe a larger refactoring is likely needed for this to be compatible with 0.4.0.

**Comment by pmikolajczyk41** [comment]
@weikengchen thank you!

**Pull request merged**
